### ISSUE TITLE
Why the initial loss is large when I train the network using the best model? 

### ISSUE THREAD

**Issue by MickeyLQ** [facebookresearch/maskrcnn-benchmark#1190]
## ❓ Questions and Help
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://Caffe2Detectron/COCO/35857890/e2e_faster_rcnn_R-101-FPN_1x"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  CHECKPOINT_PERIOD: 2500
  BASE_LR: 0.0000005
  WEIGHT_DECAY: 0.0001
  STEPS: [0, 30000, 40000]
  MAX_ITER: 10000
  IMS_PER_BATCH: 1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 100
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
OUTPUT_DIR: ./log/r50FPN2
TEST:
  IMS_PER_BATCH: 1
```
`2019-12-13 14:19:22,077 maskrcnn_benchmark.trainer INFO: Start training
2019-12-13 14:19:27,445 maskrcnn_benchmark.trainer INFO: eta: 0:44:37  iter: 20  loss: 1.7994 (1.8530)  loss_classifier: 0.8957 (0.9639)  loss_box_reg: 0.0467 (0.0626)  loss_objectness: 0.7632 (0.7644)  loss_rpn_box_reg: 0.0218 (0.0620)  time: 0.2317 (0.2683)  data: 0.0026 (0.0428)  lr: 0.000000  max mem: 1699
2019-12-13 14:19:32,170 maskrcnn_benchmark.trainer INFO: eta: 0:41:52  iter: 40  loss: 2.0140 (1.9522)  loss_classifier: 1.0788 (1.0123)  loss_box_reg: 0.0846 (0.0819)  loss_objectness: 0.7495 (0.7588)  loss_rpn_box_reg: 0.0642 (0.0992)  time: 0.2376 (0.2523)  data: 0.0039 (0.0236)  lr: 0.000000  max mem: 1767
`
1. Why the loss is large?
2. How to train the model based on catalog://Caffe2Detectron/COCO/35857890/e2e_faster_rcnn_R-101-FPN_1x?
3. Why the loss is larger than initial loss?
