### ISSUE TITLE
Prediction completely going wrong with own dataset training

### ISSUE THREAD

**Issue by shivSD** [facebookresearch/maskrcnn-benchmark#1191]
## ❓ Questions and Help
I have trained my own dataset in COCO format for 360000 iterations (2 classes = background + object) using 4 GPU, the prediction results are bad it detects patches on the object (multiple small patches with bounding box on a single object). I have looked at images of dataset both box and segmentation in COCODataset.__getitem__() and they look good so input dataset is correct.  Here is the command line i have used for training also the config used for training. Please can you let me know if there is anything wrong in the config file or command line 

One more question does test data resolution has to match training data resolution ? 

**training command**
` python3 -m torch.distributed.launch --nproc_per_node=$NGPUS tools/train_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x_castle.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.005 SOLVER.MAX_ITER 360000 SOLVER.STEPS "(240000, 320000)" SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 1 MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN 8000`

**config file**

```
DATALOADER: {ASPECT_RATIO_GROUPING: true, NUM_WORKERS: 4, SIZE_DIVISIBILITY: 32}
DATASETS:
  TEST: [coco_object_val]
  TRAIN: [coco_object_train, coco_object_val]
DTYPE: float32
INPUT:
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  HUE: 0.0
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: [800]
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1.0, 1.0, 1.0]
  SATURATION: 0.0
  TO_BGR255: true
  VERTICAL_FLIP_PROB_TRAIN: 0.0
MODEL:
  BACKBONE: {CONV_BODY: R-50-FPN, FREEZE_CONV_BODY_AT: 2}
  CLS_AGNOSTIC_BBOX_REG: false
  DEVICE: cuda
  FBNET:
    ARCH: default
    ARCH_DEF: ''
    BN_TYPE: bn
    DET_HEAD_BLOCKS: []
    DET_HEAD_LAST_SCALE: 1.0
    DET_HEAD_STRIDE: 0
    DW_CONV_SKIP_BN: true
    DW_CONV_SKIP_RELU: true
    KPTS_HEAD_BLOCKS: []
    KPTS_HEAD_LAST_SCALE: 0.0
    KPTS_HEAD_STRIDE: 0
    MASK_HEAD_BLOCKS: []
    MASK_HEAD_LAST_SCALE: 0.0
    MASK_HEAD_STRIDE: 0
    RPN_BN_TYPE: ''
    RPN_HEAD_BLOCKS: 0
    SCALE_FACTOR: 1.0
    WIDTH_DIVISOR: 1
  FPN: {USE_GN: false, USE_RELU: false}
  GROUP_NORM: {DIM_PER_GP: -1, EPSILON: 1.0e-05, NUM_GROUPS: 32}
  KEYPOINT_ON: false
  MASK_ON: true
  META_ARCHITECTURE: GeneralizedRCNN
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    DEFORMABLE_GROUPS: 1
    NUM_GROUPS: 1
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STAGE_WITH_DCN: [false, false, false, false]
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: true
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    WIDTH_PER_GROUP: 64
    WITH_MODULATED_DCN: false
  RETINANET:
    ANCHOR_SIZES: [32, 64, 128, 256, 512]
    ANCHOR_STRIDES: [8, 16, 32, 64, 128]
    ASPECT_RATIOS: [0.5, 1.0, 2.0]
    BBOX_REG_BETA: 0.11
    BBOX_REG_WEIGHT: 4.0
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
    INFERENCE_TH: 0.05
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    NMS_TH: 0.4
    NUM_CLASSES: 2
    NUM_CONVS: 4
    OCTAVE: 2.0
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: 0
    USE_C5: true
  RETINANET_ON: false
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: FPN2MLPFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 2
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: [0.25, 0.125, 0.0625, 0.03125]
    PREDICTOR: FPNPredictor
    USE_GN: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
    BG_IOU_THRESHOLD: 0.5
    DETECTIONS_PER_IMG: 100
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.5
    POSITIVE_FRACTION: 0.25
    SCORE_THRESH: 0.05
    USE_FPN: true
  ROI_KEYPOINT_HEAD:
    CONV_LAYERS: [512, 512, 512, 512, 512, 512, 512, 512]
    FEATURE_EXTRACTOR: KeypointRCNNFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: [0.0625]
    PREDICTOR: KeypointRCNNPredictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
  ROI_MASK_HEAD:
    CONV_LAYERS: [256, 256, 256, 256]
    DILATION: 1
    FEATURE_EXTRACTOR: MaskRCNNFPNFeatureExtractor
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: [0.25, 0.125, 0.0625, 0.03125]
    POSTPROCESS_MASKS: false
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: false
    USE_GN: false
  RPN:
    ANCHOR_SIZES: [32, 64, 128, 256, 512]
    ANCHOR_STRIDE: [4, 8, 16, 32, 64]
    ASPECT_RATIOS: [0.5, 1.0, 2.0]
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_PER_BATCH: true
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TRAIN: 8000
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 2000
    RPN_HEAD: SingleConvRPNHead
    STRADDLE_THRESH: 0
    USE_FPN: true
  RPN_ONLY: false
  WEIGHT: catalog://ImageNetPretrained/MSRA/R-50
OUTPUT_DIR: .
PATHS_CATALOG: /home/ubuntu/segementation/maskrcnn-benchmark/maskrcnn_benchmark/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.005
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 2500
  GAMMA: 0.1
  IMS_PER_BATCH: 8
  MAX_ITER: 360000
  MOMENTUM: 0.9
  STEPS: [240000, 320000]
  TEST_PERIOD: 0
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
TEST:
  BBOX_AUG:
    ENABLED: false
    H_FLIP: false
    MAX_SIZE: 4000
    SCALES: []
    SCALE_H_FLIP: false
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 1
```
