### ISSUE TITLE
I have negative coordinates in output from Anchor Generator

### ISSUE THREAD

**Issue by kshpv** [facebookresearch/maskrcnn-benchmark#1209]
## ❓ Questions and Help
Hello, guys!
I am using my own created backbone, whose output is [N, 1024, 15,20]
My config file:
```
MODEL:
  META_ARCHITECTURE: "DepthRCNN"
  BACKBONE:
    CONV_BODY: "RedNet-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 7
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
    SHARE_BOX_FEATURE_EXTRACTOR: True
  MASK_ON: True
  RETINANET:
    NUM_CLASSES: 7
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_test",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 200
TEST:
  IMS_PER_BATCH: 1

```
Should I change config file or anchor generator code?
Thank you!
