### ISSUE TITLE
Prediction on part of the image

### ISSUE THREAD

**Issue by Phyllis9811** [facebookresearch/maskrcnn-benchmark#915]
## ❓ Questions and Help
Hi, I trained my model with the following configuration:
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (16, 32, 48, 64, 128)
    ANCHOR_STRIDE: (2, 4, 8, 16, 32)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 2000
  ROI_HEADS:
    USE_FPN: True
    DETECTIONS_PER_IMG: 320
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_image_train", )
  TEST: ("coco_image_train",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  #reducing the base lr by x0.1 at the given timesteps
  STEPS: (50000, )
  MAX_ITER: 36000
  IMS_PER_BATCH: 2
#Added
INPUT:
  MAX_SIZE_TRAIN: 160
  MAX_SIZE_TEST: 160
  MIN_SIZE_TRAIN: (160,)
  MIN_SIZE_TEST: 160
TEST:
  IMS_PER_BATCH: 1
  DETECTIONS_PER_IMG: 500
```
And when I visualized my prediction on the image, it seems like the model only predicts on the upper left area.
![image](https://user-images.githubusercontent.com/32347588/59883264-73d6cf80-9382-11e9-974d-630af1a165f8.png)
My speculation is that my `ANCHOR_STRIDE` and `ANCHOR_SIZES` are not appropriate. Before I overwrote these values used in the `e2e_mask_rcnn_R_101_FPN_1x.yaml`, despite the poor performance, the model could predict on the whole image. Yet I fail to figure out the real problem. Any suggestion is appreciated. Thanks!
