### ISSUE TITLE
Unable to identify large features 

### ISSUE THREAD

**Issue by Phyllis9811** [facebookresearch/maskrcnn-benchmark#935]
## ❓ Questions and Help
I am training a model on a custom dataset, and I am having difficulty getting the model to identify large features. I'm predicting on fluorescent images for tissue and the images contain larger cells and model predicts really bad on those cells. I experimented with different anchor sizes but that didn't seem to help. Currently, I'm using `ANCHOR_SIZES: (16, 32, 48, 64, 128)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)` and the cells that the model failed to identity have sizes around `70*70` and my image size is `160*160`. Initially I used configurations from `e2e_mask_rcnn_R_101_FPN_1x.yaml` and when I switched to `e2e_mask_rcnn_X_101_32x8d_FPN_1x.yaml`, the AP increased from 0.43 to 0.63 but there's still room for improvement since the model still performs badly on large cells. What can I do to make my model better identify large features? Many thanks.

My configuration is the following:
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (16, 32, 48, 64, 128)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000 
    FPN_POST_NMS_TOP_N_TEST: 2000
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.05
    NMS: 0.7
    DETECTIONS_PER_IMG: 3000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_image_train", )
  TEST: ("coco_image_train",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 2
INPUT:
  MAX_SIZE_TRAIN: 160
  MAX_SIZE_TEST: 160
  MIN_SIZE_TRAIN: (160,)
  MIN_SIZE_TEST: 160
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1., 1., 1.]
  TO_BGR255: True
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  SATURATION: 0.0
  HUE: 0.0
TEST:
  IMS_PER_BATCH: 1
  DETECTIONS_PER_IMG: 500

```
